name: nightly

on:
  # Build master branch only
  push:
    branches:
      - master
  # Build pull requests targeting master branch only
  pull_request:
    branches:
      - master

jobs:
  test:
    name: nightly on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Test default features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all -- --nocapture

      - name: Test parser feature
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-features -- --nocapture
